-- Inserir serviços no banco de dados
INSERT INTO servicos (nome) VALUES 
('Academias'),
('Acupuntura'),
('Alergologia'),
('Aromaterapia'),
('Arquitetura'),
('Assessorias'),
('Assistente Terapêutico'),
('Auto Escola'),
('Calçados'),
('Cardiologia e Cirurgia Cardiovascular'),
('Cardiologista'),
('Arritmologia'),
('Certificadora Digital'),
('Cirurgia de Cabeça e Pescoço'),
('Cirurgia do Aparelho Digestivo'),
('Cirurgia Geral'),
('Cirurgia Oncológica'),
('Cirurgia Pediátrica'),
('Cirurgia Plástica'),
('Cirurgia Torácica'),
('Citopatologia'),
('Clínica Médica'),
('Clínico Geral'),
('Consultorias'),
('Corretora de Imóveis'),
('Corretora de Seguros'),
('Cultura e Lazer'),
('Dermatologia'),
('Design Gráfico'),
('Diagnóstico por Imagem'),
('Web Design'),
('Educação'),
('Endocrinologia'),
('Metabologia'),
('Endoscopia'),
('Equipamentos de Reabilitação'),
('Escritórios Compartilhados'),
('Escritórios Virtuais'),
('Estética'),
('Estética e Beleza'),
('Eventos'),
('Farmácias e Drogarias'),
('Fisioterapia'),
('Floricultura'),
('Fonoaudiologia'),
('Gastroenterologia'),
('Genética Médica'),
('Geriatria'),
('Ginecologia'),
('Obstetrícia'),
('Hematologia'),
('Homeopatia'),
('Hiperbárica Preventiva'),
('Homecare'),
('Hotelaria'),
('Idiomas'),
('Infectologia'),
('Informática'),
('Jóias e Semijoias'),
('Laboratórios de Análises Clínicas'),
('Lava-Jato'),
('Lavanderia'),
('Livrarias'),
('Locadora'),
('Manutenção e Acessórios de Comunicação'),
('Massoterapia'),
('Mastologia'),
('Médico Nuclear'),
('Móveis Planejados'),
('Nefrologia'),
('Neurologia'),
('Neurocirurgia'),
('Neuropediatria'),
('Neuropsicologia'),
('Neuropsicopedagogia'),
('Nutrição'),
('Odontologia'),
('Oftalmologia'),
('Oncologia'),
('Ortopedia e Traumatologia'),
('Ótica'),
('Otorrinolaringologia'),
('Pediatria'),
('Perito'),
('Pilates'),
('Pneumologia'),
('Proctologia'),
('Produção Cinematográfica'),
('Psicologia'),
('Psicomotricidade'),
('Psicopedagogia'),
('Psicoterapia'),
('Psiquiatria'),
('Quiropraxia'),
('Radiologia'),
('Radioterapia'),
('Restaurantes e Docerias'),
('Reumatologia'),
('Alergia e Imunologia'),
('Anestesiologia'),
('Angiologia e Cirurgia Vascular'),
('Cardiologia'),
('Segurança'),
('Serviços Alimentícios'),
('Serviços Automotivos'),
('Serviços Contábeis'),
('Serviços de Limpeza'),
('Serviços de Manutenção'),
('Serviços de Segurança'),
('Serviços Funerários'),
('Software Jurídico'),
('Terapia'),
('Terapia Ocupacional'),
('Turismo e Viagem'),
('Urologia'),
('Vestuário'),
('Veterinária e Pets')
ON CONFLICT DO NOTHING;