// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdqefvncjifjycsaxnex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkcWVmdm5jamlmanljc2F4bmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTYyNTcsImV4cCI6MjA3MjkzMjI1N30.FFJrOK0ZqHqxEhMpD1ReiRJYmZCiEYDJ1wEQ7h5yxxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});